### ISSUE TITLE
Even not using same client id any where else, We are getting errors to connect with specific client id?

### ISSUE THREAD

**Issue by namjithwisilica** [vernemq/vernemq#1028]
Since i know mqtt not allowing duplicate client id, I am not using same client id anywhere, However  i could not  connect to a specific client id again. I have restarted the broker . But still getting error. And i have created a new client id and tried, its working. So please tell , Is anywhere vernemq is keeping the clientid. If keeping is there any way to clear this info.

**Comment by larshesel** [comment]
Hi, without more information it's hard to give any advice. What error does your MQTT client report when you cannot connect? Is there anything in the logs?

**Comment by namjithwisilica** [comment]
This is the error i am getting. Could you please look into this.

org.eclipse.paho.client.mqttv3.MqttException: MqttException
at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:438) ~[com.wisilica.streaming.tag-1.0-jar-with-dependencies.jar:?]
at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:424) ~[com.wisilica.streaming.tag-1.0-jar-with-dependencies.jar:?]
at com.wisilica.streaming.tag.TagReader.connectComplete(TagReader.java:229) [com.wisilica.streaming.tag-1.0-jar-with-dependencies.jar:?]
at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onSuccess(ConnectActionListener.java:104) [com.wisilica.streaming.tag-1.0-jar-with-dependencies.jar:?]
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.fireActionEvent(CommsCallback.java:321) [com.wisilica.streaming.tag-1.0-jar-with-dependencies.jar:?]
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleActionComplete(CommsCallback.java:260) [com.wisilica.streaming.tag-1.0-jar-with-dependencies.jar:?]
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:190) [com.wisilica.streaming.tag-1.0-jar-with-dependencies.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:844) [?:?]

**Comment by larshesel** [comment]
Sorry I cannot help you with that - there's nothing in that stacktrace that hints to any problem - it only shows a generic MQTT exception. why does your client throw this exception?

As I asked: is there anything in the logs? Further, what does `vmq-admin trace` say for the client when it connects to the node? Does it even reach the node?

**Comment by namjithwisilica** [comment]
While running this command "sudo vmq-admin trace client client-id=tag_sub_1" i am getting the following.

<7251.20312.43> Hook returned "ok"
<7251.20306.43> Trace session for tag_sub_1 stopped
<7251.20312.43> MQTT SEND: CID: "tag_sub_1" CONNACK(sp: 0, rc: 0)
<7251.20312.43> MQTT RECV: CID: "tag_sub_1" SUBSCRIBE(m1422) with topics:
q:1, t: "1/tag/1/3/1"
<7251.20312.43> Calling auth_on_subscribe(tag,{[],<<"tag_sub_1">>}) with topics:
q:1, t: "1/tag/1/3/1"
<7251.20312.43> Hook returned {error,error}
<7251.20312.43> MQTT SEND: CID: "tag_sub_1" SUBACK(m1422, qt[not_allowed])
New session with PID <7251.20321.43> found for client "tag_sub_1"
<7251.20321.43> MQTT RECV: CID: "tag_sub_1" CONNECT(c: tag_sub_1, v: 4, u: tag, p: Q1werty@123, cs: 1, ka: 180)
<7251.20321.43> Calling auth_on_register({{172,31,70,115},2264},{[],
<<"tag_sub_1">>},tag,*******password*****,true)

**Comment by namjithwisilica** [comment]
Following is the this command "sudo vmq-admin session show" output. Is there any issue multiple clientid under one user? Because under tag user i have more than one clientid.
+-----------+---------+----------+-------------+---------+----+
| client_id |is_online|mountpoint| peer_host |peer_port|user|
+-----------+---------+----------+-------------+---------+----+
| mqtt_pub1 | true | |172.31.77.169| 2302 |tag |
|mqttpub_sub| true | |172.31.70.115| 6030 |tag |
| 1465 | false | | null | null |null|
| 1466 | false | | null | null |null|
| tag_sub_1 | true | |172.31.43.150| 40438 |tag |
| gmi_pub | true | |172.31.70.115| 6000 |gmi |
| dmc_pub | true | |172.31.43.150| 40286 |dmc |
+-----------+---------+----------+-------------+---------+----+

**Comment by larshesel** [comment]
You can use as many client-ids as you wish for a username/password. Which version of VerneMQ are you using and is `allow_multiple_sessions` set to on? And again: is there anything in the logs?

**Comment by namjitharavind** [comment]
Thank you very much for the reply. Since allow_multiple_sessions=on is not recommended in cluster. I am using unique username across cluster. And this working awesome. Again thank a lot.
