### ISSUE TITLE
How to create unit test for vernemq plugin?

### ISSUE THREAD

**Issue by pewh** [vernemq/vernemq#1097]
I don't see any resource to create unit test for plugin. My use case is for testing some custom ACL (on_auth_registered, on_auth_subscribe).

**Comment by NickNeck** [comment]
You can make unit tests as usual.
```
defmodule MyPluginTest do
  use ExUnit

  import MyPlugin

  test "do it" do
    ... some code ...
    assert auth_on_subscribe(:undef, {:undef, client_id}, [{topic, 0}]) == :next
  end
end
```
The `:undef`s are params I am not use in my tests.

**Comment by pewh** [comment]
Hi, sorry for late response. Unfortunately, mine still got error.

```
defmodule ChatAclTest do
  use ExUnit.Case

  test "do it" do
    clientid = "123"
    username = "456"
    password = "789"

    topic = "asd"

    # assert auth_on_register(:undef, {:undef, clientid}, username, password, false) == :next

    assert auth_on_subscribe(:undef, {:undef, clientid}, [{topic, 0}]) == :next
  end
end
```

> mix test

```
warning: variable "password" is unused
  test/chat_acl_test.exs:7

warning: variable "username" is unused
  test/chat_acl_test.exs:6


== Compilation error in file test/chat_acl_test.exs ==
** (CompileError) test/chat_acl_test.exs:13: undefined function auth_on_subscribe/3
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:209: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by larshesel** [comment]
This is an elixir error which says that you're calling and undefined function, in this case `auth_on_subscribe/3`. You probably need to either import it or prefix it with the module name where it is defined. I would recommend brushing up on programming Elixir so you get a good understanding on how to program with it and understand the error messages.
