### ISSUE TITLE
Clients gets regularly disconnected

### ISSUE THREAD

**Issue by francois-travais** [vernemq/vernemq#1413]
### Environment

- VerneMQ Version: 1.9.2 and earlier
- OS: CentOS 7
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf), the changes from the default:
```
allow_register_during_netsplit = on
allow_publish_during_netsplit = on
allow_subscribe_during_netsplit = on
allow_unsubscribe_during_netsplit = on
max_client_id_size = 200
max_inflight_messages = 0
max_online_messages = 500000
max_offline_messages = 500000
listener.nr_of_acceptors = 100
listener.tcp.default = PRIVATE_IP:1883
listener.tcp.kafka_listeners = PRIVATE_IP:1884
listener.vmq.clustering = PRIVATE_IP:44053
listener.http.metrics = PRIVATE_IP:9102
nodename = VerneMQ@PRIVATE_HOSTNAME
erlang.async_threads = 128
erlang.distribution.port_range.minimum = 50000
erlang.distribution.port_range.maximum = 61000
```
- Cluster size/standalone: 2 nodes

### Expected behavior

I expect my clients not to get disconnected every 30~60s.

### Actual behaviour

My clients are java-based microservices taking messages from VerneMQ and forwarding them to Kafka. They very basic and run on kubernetes.
The initial implementation used Paho library, lately I've refactored it to use HiveMQ client and get the same result.

I can see these lines in `console.log`:
```
2020-01-17 07:51:10.867 [info] <0.6728.144>@plumtree_metadata_exchange_fsm:exchange:165 completed metadata exchange with 'VerneMQ@PRIVATE_HOSTNAME'. repaired 0 missing local prefixes, 0 missing remote 
prefixes, and 1 keys
2020-01-17 07:51:10.962 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.6285.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_que
ue_len,0}] #Port<0.93740>
2020-01-17 07:51:12.211 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.6798.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_que
ue_len,0}] #Port<0.93741>
2020-01-17 07:51:14.738 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.6929.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_que
ue_len,0}] #Port<0.93743>
2020-01-17 07:51:18.472 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.7132.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_que
ue_len,0}] #Port<0.93748>
2020-01-17 07:51:22.495 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.7323.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_que
ue_len,0}] #Port<0.93753>
2020-01-17 07:51:26.936 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.7508.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_que
ue_len,0}] #Port<0.93757>
2020-01-17 07:51:29.169 [warning] <0.7693.144>@vmq_ranch:teardown:159 session stopped abnormally due to 'badarg'
2020-01-17 07:51:30.602 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.7719.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_que
ue_len,0}] #Port<0.93761>
2020-01-17 07:51:30.891 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.7732.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_que
ue_len,0}] #Port<0.93762>
2020-01-17 07:51:33.262 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.7894.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_que
ue_len,0}] #Port<0.93763>
2020-01-17 07:51:35.499 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.7982.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_que
ue_len,0}] #Port<0.93764>
2020-01-17 07:51:35.934 [info] <0.167.0>@vmq_sysmon_handler:handle_event:100 monitor got {suppressed,port_events,1}
2020-01-17 07:51:36.075 [info] <0.167.0>@vmq_sysmon_handler:handle_event:95 monitor busy_port <0.8016.144> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,0}] #Port<0.93766>
```
The more worrying line is probably:
```
2020-01-17 07:51:29.169 [warning] <0.7693.144>@vmq_ranch:teardown:159 session stopped abnormally due to 'badarg'
```
I've always 2 clients subscribed to `$share/kafka_producer/devices/#` and one device sending data to various topics with prefix `devices/`. The device sends approximately 60msg/s, and usually the error doesn't show up, but if the subscribers are a bit late or their queues a bit full, then the `'badarg'` shows up.

On the client side I get these with HiveMQ client:
```
2020-01-16 14:35:01,896 [com.hivemq.client.mqtt-1-1] ERROR c.h.c.i.m.h.d.MqttDisconnectHandler - Exception while disconnecting.
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(...)(Unknown Source)
```
With Paho these:
```
Connection to MQTT broker lost
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
    at org.eclipse.paho.client.mqttv3.internal.CommsSender.handleRunException(CommsSender.java:182) [org.eclipse.paho.client.mqttv3-1.2.0.jar:na]
    at org.eclipse.paho.client.mqttv3.internal.CommsSender.run(CommsSender.java:163) [org.eclipse.paho.client.mqttv3-1.2.0.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_222]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_222]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
    at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115) ~[na:1.8.0_222]
    at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[na:1.8.0_222]
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_222]
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_222]
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttOutputStream.flush(MqttOutputStream.java:49) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:na]
    at org.eclipse.paho.client.mqttv3.internal.CommsSender.run(CommsSender.java:132) [org.eclipse.paho.client.mqttv3-1.2.0.jar:na]
    ... 7 common frames omitted
```

**Comment by francois-travais** [comment]
Here are some info of the system buffer sizes:
```
$ cat /proc/sys/net/ipv4/tcp_rmem 
4096	87380	6291456
$ cat /proc/sys/net/ipv4/tcp_wmem
4096	16384	4194304
$ cat /proc/sys/net/ipv4/tcp_mem 
188688	251587	377376
```

**Comment by ioolkos** [comment]
OK, client side the error seems to signal that the client tries to send into an already closed channel.
Server side, the teardown of the socket isn't happening normally either. 

Plus, we have shared subscribers. Need to do some thinking on this, but I wonder what an actual Wireshark capture would show. Maybe this is also a RST vs FIN thing.

**Comment by francois-travais** [comment]
HiveMQ client isn't really verbose. I think indeed the error shown is due to the client trying to send an unsubscribe or what not after the connection get closed.
However Paho's output is quite clear.

**Comment by ioolkos** [comment]
Do you see any more information in error.log or crash.log?
Because the interesting thing from VerneMQ side is that the "busy_port" is always signaled for another port and another session. So there must be some re-connects immediately.

So I guess the clients also log their warnings accordingly in series?

What happens when you connect just one normal subscriber to that topic, instead of shared subscribers?

**Comment by dergraf** [comment]
I still think the clients are getting overloaded with messages from VerneMQ. A simple fix for this is to set the max_inflight_messages to something bigger than 0 (you've changed the default 20 to 0 in your config), I assume you're using QoS > 0 here.

**Comment by francois-travais** [comment]
@dergraf That's a good idea, I'll try that out.

**Comment by francois-travais** [comment]
@dergraf It worked! I've set `max_inflight_messages` to 20, but it wasn't fats enough to consume bothe the normal flow plus the messages stores in the queue. So I set it to 100 and that was enough to consume both stored messages and normal traffic. I'm good to go now, thanks @ioolkos and @dergraf!
