### ISSUE TITLE
SSL Connection issue in ubuntu 16.04

### ISSUE THREAD

**Issue by achandana** [vernemq/vernemq#1469]
I am working on SSL certificate authorization and authentication. Vernemq configuration as below.

listener.ssl.cafile = /etc/vernemq/ssl/CA-cert.pem
listener.ssl.certfile = /etc/vernemq/ssl/server-cert.pem
listener.ssl.keyfile = /etc/vernemq/ssl/server-key.pem
listener.ssl.require_certificate = on
listener.ssl.default = 127.0.0.1:8883
listener.ssl.use_identity_as_username = on

I am using java program as client for vernemq. 
		String serverUrl = "ssl://127.0.0.1:8883";
		  String caFilePath = "/etc/vernemq/ssl/CA-cert.pem"; 
                 String clientCrtFilePath  = "/etc/vernemq/ssl/john.crt"; 
               String clientKeyFilePath =  "/etc/vernemq/ssl/john.key";
		 
		
		MqttClient client;
		try {
			client = new MqttClient(serverUrl, "john");
			MqttConnectOptions options = new MqttConnectOptions();			
			 options.setUserName("john");
			 options.setPassword("root".toCharArray());
			 options.setConnectionTimeout(100);
			options.setCleanSession(false);
			SSLSocketFactory socketFactory = getSocketFactory(caFilePath, clientCrtFilePath, clientKeyFilePath, "root");
			options.setSocketFactory(socketFactory);
			System.out.println("starting connect the server...");
			client.connect(options);
			System.out.println("connected!");
			Thread.sleep(1000);		client.subscribe("/u/56ca327d17531d08e76bddd4a215e37f5fd6082f7442151c4d3f1d100a0ffd4e", 0);
			client.disconnect();
			System.out.println("disconnected!");

I am able to connect to vernemq using tcp://127.0.0.1:1883 but I am not able to connect to ssl://127.0.0.1:8883. I am getting the below error in java console. Any one can help to fix this issue. 

I am using self signed certificates.

MqttException (0) - java.net.SocketException: Connection reset
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.waitForClose(SSLSocketImpl.java:1761)
	at sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:124)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1079)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1479)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1346)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701)
	... 7 more

**Comment by ioolkos** [comment]
@achandana firsts thing to test is whether you can connect to the server using OpenSSL tools, with the same client certs. You can find a couple of hints on how to do that over at RabbitMQ: https://www.rabbitmq.com/troubleshooting-ssl.html#openssl-tools
