### ISSUE TITLE
V1.12.1 issue: Connection refused to VerneMQ server since 7/23/2021

### ISSUE THREAD

**Issue by bliusb** [vernemq/vernemq#1853]
It worked fine before 7/22/2021. Found out that you just updated to 1.12.1 between 7/22 and 7/23. Now we can't connect to the vernemq. Could you please let us know what have been changed from 1.11.0 to 1.12.1?

Here is the log:

> OnConnectingFailed [Exception]:       MQTTnet.Exceptions.MqttCommunicationException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(IPAddress address, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.Socket.ConnectAsync(String host, Int32 port)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, String host, Int32 port)
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.ReconnectIfRequiredAsync()
OnDisconnected [ClientWasConnected]:       False
OnDisconnected [AuthenticateResult]:       
OnDisconnected [Exception]:       MQTTnet.Exceptions.MqttCommunicationException: Connection refused

### Environment

- VerneMQ Version:1.12.1
- OS:
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behaviour

- Please describe the expected behaviour.

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

**Comment by ioolkos** [comment]
@bliusb thanks... this is a client log that tells you the connection was refused. It's not enough information to allow me to help. First thing to do is to check whether the MQTT listener(s) are actually up (`vmq-admin listener show`).

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.
