### ISSUE TITLE
SSL/TLS (X.509 Certificate) not working with Root/Intermediate Key Pairs & CA Chain of Trust.

### ISSUE THREAD

**Issue by chouhan** [vernemq/vernemq#907]
### Environment

- VerneMQ Version: 'FROM erlio/docker-vernemq:latest'
- OS: Windows 10
- Erlang/OTP version (if building from source):
- AWS EKS Cluster
- Kubernetes Version: 1.10
- Platform Version: eks.2

### Expected behavior

I am expecting a connection to be established via TLS (with Root/Intermediate Key Pairs and a CA Chain of Trust certificate)

Here are the most relevant vernemq configurations

listener.ssl.cafile = /etc/ssl/ca-chain.cert.pem
listener.ssl.certfile = /etc/ssl/server.cert.pem
listener.ssl.keyfile = /etc/ssl/server.key.pem
listener.ssl.require_certificate = on
listener.ssl.depth = 2
allow.anonymous = off
vmq_passwd.password_file = /etc/vernemq-passwd/vmq.passwd

Here is the kubernetes deployment file (deliberately changed extension to upload to github)

[vernemq-certifications.txt](https://github.com/erlio/vernemq/files/2511198/vernemq-certifications.txt)
[vernemq-cluster.txt](https://github.com/erlio/vernemq/files/2511199/vernemq-cluster.txt)
[vernemq-passwd.txt](https://github.com/erlio/vernemq/files/2511200/vernemq-passwd.txt)

This is what I am trying to achieve https://github.com/erlio/vernemq/issues/551#issuecomment-352428402

This issue is similar to https://github.com/erlio/vernemq/issues/680, but not the same since it was not deployed on Kubernetes Container.

#### Resource: 

https://jamielinux.com/docs/openssl-certificate-authority/index.html

Note: the passwords is 'secretpassword' for both root key and intermediate key

#### Setup

cd C:\mqtt-k8s-eks

mkdir ri-certs

cd ri-certs

mkdir /root/ca

cd /root/ca

mkdir certs crl newcerts private

create index.txt file. In unix you can "touch index.txt"

echo 1000 > serial

Copy openssl.cnf setting from https://jamielinux.com/docs/openssl-certificate-authority/appendix/root-configuration-file.html
and paste it in /root/ca folder

#### Creating root key pair

Ensure that you are in /root/ca folder

// Create Root Key (Password that I issues is 'secretpassword'')

openssl genrsa -aes256 -out private/ca.key.pem 4096 

// Create Root Certificate Authority (or call it as rootca.cert.pem)

openssl req -config openssl.cnf -key private/ca.key.pem -new -x509 -days 2038 -sha256 -extensions v3_ca -out certs/ca.cert.pem

Note: You cannot push days beyond 2038, if using openssl on windows.

// Verify root certificate

openssl x509 -noout -text -in certs/ca.cert.pem

#### Creating intermediate pair

mkdir /root/ca/intermediate

cd intermediate

mkdir certs crl csr newcerts private

echo index.txt

echo 1000 > serial

echo 1000 > crlnumber

Copy openssl.cnf to generate intermediate key pair's from https://jamielinux.com/docs/openssl-certificate-authority/_downloads/intermediate-config.txt to intermediate folder.

cd root/ca

//Create a intermediate key

openssl genrsa -aes256 -out intermediate/private/intermediate.key.pem 4096

// Create a certificate signing request (CSR) using intermediate key and intermediate/openssl.cnf file

openssl req -config intermediate/openssl.cnf -new -sha256 -key intermediate/private/intermediate.key.pem -out intermediate/csr/intermediate.csr.pem

Note: The details of this CSR should match the Root CA. The common name of this CSR should be different from Root CA.

// Create a intermediate certificate authority (Intermediate CA or call it as intermediateca.cert.pem). This uses Root CA with v3_intermediate_ca extension to sign intermediate CSR. This should use the root/ca/openssl.cnf config file

openssl ca -config openssl.cnf -extensions v3_intermediate_ca -days 3650 -notext -md sha256 -in intermediate/csr/intermediate.csr.pem -out intermediate/certs/intermediate.cert.pem

// Now, verify this certificate entry will be updates in the certificate database, which is the index.txt file in root/ca folder.

//Additionally, you may also verify the intermediate certificate

openssl x509 -noout -text -in intermediate/certs/intermediate.cert.pem

// Verify the intermediate certificate against the root certificate

openssl verify -CAfile certs/ca.cert.pem intermediate/certs/intermediate.cert.pem

#### Chain of Trust

// When a application tries to verify a certificate issued by intermediate CA, it must also verify the intermediate certificate against the root certificate. To complete the chain of trust, create a CA certificate chain to present to the application

type intermediate/certs/intermediate.cert.pem certs/ca.cert.pem > intermediate/certs/ca-chain.cert.pem

// The same command with full path works

type "C:\mqtt-k8s-eks\ri-certs\root\ca\intermediate\certs\intermediate.cert.pem" "C:\mqtt-k8s-eks\ri-certs\root\ca\certs\ca.cert.pem" > "C:\mqtt-k8s-eks\ri-certs\root\ca\intermediate\certs\ca-chain.cert.pem"

We will use this chain of trust CA while using device authorization. Also, the chain of trus CA will be part of vernemq server.

#### Create & Sign server(vernemq broker) and client (device) certificates

We will be signing certificates using our intermediate CA.

#### Now, we first create server certificates key pair

// Create a Key for VerneMQ Server

If you've noticed, the root and the intermediate key's are created using 4096 bits, which is more secure than 2048.

cd root/ca/intermediate

openssl genrsa -aes256 -out private/server.key.pem 2048

// password is "secretpassword"

// Create a CSR using the above key for devices. The CSR details don’t need to match the intermediate CA. 
// For server certificates, the Common Name must be a fully qualified domain name (eg, www.example.com), 
// whereas for client certificates it can be any unique identifier (eg, an e-mail address). 
// Note that the Common Name cannot be the same as either your root or intermediate certificate.

openssl req -config openssl.cnf -key private/server.key.pem -new -sha256 -out csr/server.csr.pem

// Create a Certificate

cd root/ca/intermediate

To create a certificate, use the intermediate CA to sign the CSR. 
If the certificate is going to be used on a server, use the server_cert extension. 
If the certificate is going to be used for user authentication, use the usr_cert extension

openssl ca -config openssl.cnf -extensions server_cert -days 375 -notext -md sha256 -in csr/server.csr.pem -out certs/server.cert.pem

// Verify the Certificate

openssl x509 -noout -text -in certs/server.cert.pem

##### Now, we create device certificates key pair

// Create a Key for the Device.

cd root/ca/intermediate

openssl genrsa -aes256 -out private/device.key.pem 2048

// password is "secretpassword"

// Create a CSR using the above key for devices. The CSR details don’t need to match the intermediate CA. 
// For server certificates, the Common Name must be a fully qualified domain name (eg, www.example.com), 
// whereas for client certificates it can be any unique identifier (eg, an e-mail address). 
// Note that the Common Name cannot be the same as either your root or intermediate certificate.

openssl req -config openssl.cnf -key private/device.key.pem -new -sha256 -out csr/device.csr.pem

// Create a Certificate

cd root/ca/intermediate

To create a certificate, use the intermediate CA to sign the CSR. 
If the certificate is going to be used on a server, use the server_cert extension. 
If the certificate is going to be used for user authentication, use the usr_cert extension

// Create a Client (Device) Certificate

openssl ca -config openssl.cnf -extensions usr_cert -days 375 -notext -md sha256 -in csr/device.csr.pem -out certs/device.cert.pem

// Verify the Certificate

openssl x509 -noout -text -in certs/device.cert.pem

#### Deploy the certificate

You can now either deploy your new certificate to a server, or distribute the certificate to a client. 
When deploying to a server application (eg, Apache), you need to make the following files available:

**ca-chain.cert.pem
server.com.key.pem
server.cert.pem**

cd ri-certs

kubectl create secret generic vernemq-certifications --from-file=root/ca/intermediate/certs/ca-chain.cert.pem --from-file=root/ca/intermediate/certs/server.cert.pem --from-file=root/ca/intermediate/private/server.key.pem

TO GENERATE YAML FILE FOR THE ABOVE COMMAND

kubectl create secret generic vernemq-certifications --from-file=root/ca/intermediate/certs/ca-chain.cert.pem --from-file=root/ca/intermediate/certs/server.cert.pem --from-file=root/ca/intermediate/private/server.key.pem -o yaml > vernemq-certifications.yaml

OR

kubectl get secret vernemq-certifications -o yaml --export

#### Convert PEM to CRT and PEM to KEY

cd root/ca/intermediate

openssl x509 -outform pem -in certs/ca-chain.cert.pem -out certs/converts/ca-chain.crt

openssl x509 -outform pem -in certs/device.cert.pem -out certs/converts/device.crt

// For converting the key

openssl rsa -in private/device.key.pem -out private/converts/device.key

https://stackoverflow.com/questions/13732826/convert-pem-to-crt-and-key

#### Connections

kubectl run inner-sub --rm -it --image efrecon/mqtt-client /bin/ash

mosquitto_sub -h a02b56106d63e11e88b5e0e108ce9b8f-1053914526.us-east-1.elb.amazonaws.com -p 1883 -t devices/+/machineInfo/name -d -u inner -P inner

mosquitto_pub -h a02b56106d63e11e88b5e0e108ce9b8f-1053914526.us-east-1.elb.amazonaws.com -p 1883 -t devices/d123/machineInfo/name -d -u inner -P inner -m "Message from inner"

#### Using SSL with mosquitto

cd C:\Program Files\mosquitto

mosquitto_sub -h af28cb4dcd6d811e88b5e0e108ce9b8f-819540286.us-east-1.elb.amazonaws.com -p 8883 -t devices/+/machineInfo/name -i device-mqtt-client -d -u outer -P outer --cafile "C:/mqtt/mqtt-k8s-eks/ri-certs/root/ca/intermediate/certs/converts/ca-chain.crt" --insecure

OR

mosquitto_sub -h af28cb4dcd6d811e88b5e0e108ce9b8f-819540286.us-east-1.elb.amazonaws.com -p 8883 -t devices/+/machineInfo/name -i device-mqtt-client -d -u outer -P outer --cafile "C:/mqtt-k8s-eks/ri-certs/root/ca/intermediate/certs/ca-chain.cert.pem" --insecure

mosquitto_pub -h af28cb4dcd6d811e88b5e0e108ce9b8f-819540286.us-east-1.elb.amazonaws.com -p 8883 -t devices/lenovo/machineInfo/name -m "message from lenovo" -i device-mqtt-client -d -u outer -P outer --cafile "C:/mqtt-k8s-eks/ri-certs/root/ca/intermediate/certs/converts/ca-chain.crt" --insecure

OR

mosquitto_pub -h af28cb4dcd6d811e88b5e0e108ce9b8f-819540286.us-east-1.elb.amazonaws.com -p 8883 -t devices/lenovo/machineInfo/name -m "message from lenovo" -i device-mqtt-client -d -u outer -P outer --cafile "C:/mqtt-k8s-eks/ri-certs/root/ca/intermediate/certs/ca-chain.cert.pem" --insecure

### Issue

![image](https://user-images.githubusercontent.com/2761678/47442176-ec4ba900-d77f-11e8-8457-c9435c0343de.png)

From Mqtt.fx client

2018-10-23 12:08:07,131  INFO --- ScriptsController              : Clear console.
2018-10-23 12:08:07,131 ERROR --- BrokerConnectService           : MqttException
2018-10-23 16:00:46,949  INFO --- BrokerConnectorController      : onConnect
2018-10-23 16:00:46,953  INFO --- ScriptsController              : Clear console.
2018-10-23 16:00:46,969  INFO --- MqttFX ClientModel             : MqttClient with ID MQTT_FX_Client assigned.
2018-10-23 16:00:47,100 ERROR --- MqttFX ClientModel             : Error when connecting
org.eclipse.paho.client.mqttv3.MqttException: MqttException
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_162]
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	... 7 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_162]
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	... 7 more
2018-10-23 16:00:47,102 ERROR --- MqttFX ClientModel             : Please verify your Settings (e.g. Broker Address, Broker Port & Client ID) and the user credentials!
org.eclipse.paho.client.mqttv3.MqttException: MqttException
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_162]
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	... 7 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_162]
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	... 7 more
2018-10-23 16:00:47,109  INFO --- ScriptsController              : Clear console.
2018-10-23 16:00:47,110 ERROR --- BrokerConnectService           : MqttException

openssl s_client -connect a918da4cfd74411e8b18b0adc187157b-2031679216.us-east-1.elb.amazonaws.com:8883 -CApath "C:/Users/Rakesh Chouhan/darkops-workspace/devops/k8s/mqtt/mqtt-k8s-eks/ri-ce
rts/root/ca/intermediate/certs/converts"

![image](https://user-images.githubusercontent.com/2761678/47443265-f373b680-d781-11e8-939e-dae4725a5adc.png)

**Comment by larshesel** [comment]
Sorry for the lack of response here. Can you reproduce this issue on a single node without docker/kubernetes or is this a docker/kubernetes issue?

**Comment by ioolkos** [comment]
I have followed your steps in trying to reproduce this, and got stuck converting the certs towards the end.

It's time consuming to work on complex issues like that. We *will* try to get to it, but please do not just wait on us and investigate a little bit too (like you already have). Your help is very much appreciated!

**Comment by chouhan** [comment]
> Sorry for the lack of response here. Can you reproduce this issue on a single node without docker/kubernetes or is this a docker/kubernetes issue? The reason I ask is that if it's reproducible stand-alone it's much easier to help than having to worry about all the moving parts of kubernetes as well - with which I have little experience.

I was able to reproduce this issue on a Single node without docker/kubernetes. I documented that here..
https://github.com/erlio/vernemq/issues/551#issuecomment-412387284

**Comment by larshesel** [comment]
Closing this due to inactivity
